import type { OpcaoQuiz } from "../tipos";

function opcoes(correta: number, ...textos: string[]): OpcaoQuiz[] {
  return textos.map((texto, indice) => ({
    opcaoId: String.fromCharCode(97 + indice),
    texto,
    correta: indice === correta,
  }));
}

export const alternativasQuiz: Record<string, OpcaoQuiz[]> = {
  "eleg-1": opcoes(0, "Atenda aos critérios de ENEM, renda e escolaridade.", "Tenha diploma de curso superior.", "Não tenha feito o ENEM.", "Faça a inscrição diretamente na Feevale."),
  "eleg-2": opcoes(1, "Até 3 salários mínimos por pessoa em qualquer bolsa.", "Até 1,5 salário mínimo por pessoa para bolsa integral.", "Apenas renda familiar acima de 5 salários mínimos.", "Não existe limite de renda."),
  "eleg-3": opcoes(2, "Sim, somente escola pública é aceita.", "Sim, apenas escola privada com bolsa integral.", "Não necessariamente; há outras situações aceitas.", "Não é preciso comprovar o ensino médio."),
  "eleg-4": opcoes(0, "Não, quem já tem diploma não pode concorrer.", "Sim, qualquer diploma permite nova bolsa.", "Sim, mas somente na mesma área.", "Sim, desde que não tenha usado o ENEM."),
  "eleg-5": opcoes(3, "Não há exceções para renda ou escolaridade.", "Somente estudantes de escola pública têm exceção.", "A exceção vale para qualquer curso sem critérios.", "Professores da rede pública podem ter exceção para cursos de licenciatura e pedagogia."),
  "eleg-6": opcoes(1, "Some apenas a renda do responsável financeiro.", "Some a renda bruta e divida pelo número de pessoas.", "Divida a renda líquida pelo salário mínimo.", "Considere somente a renda do estudante."),
  "eleg-7": opcoes(2, "A renda líquida após descontos.", "Apenas o salário registrado em carteira.", "A renda familiar bruta, sem descontos.", "Somente rendimentos de trabalho formal."),
  "eleg-8": opcoes(0, "Comprovante de exercício do magistério na rede pública.", "Apenas declaração do próprio professor.", "Somente o diploma de graduação.", "Comprovante de matrícula em licenciatura."),
  "insc-1": opcoes(2, "Presencialmente na Feevale, com taxa.", "Por e-mail, sem login gov.br.", "No site oficial do PROUNI, com login gov.br.", "Em qualquer site de inscrição educacional."),
  "insc-2": opcoes(1, "Uma opção de curso.", "Até duas opções de curso e instituição.", "Até cinco opções em instituições diferentes.", "Quantas opções desejar."),
  "insc-3": opcoes(0, "Não. A inscrição é totalmente gratuita.", "Sim, há taxa obrigatória de inscrição.", "Somente a segunda opção tem taxa.", "A Feevale cobra uma taxa de garantia."),
  "insc-4": opcoes(3, "Por telefone, antes do resultado.", "Somente pela secretaria da instituição.", "Pelo resultado do ENEM.", "No site do PROUNI, na área do candidato."),
  "doc-1": opcoes(1, "Somente o comprovante de residência.", "Carteira de Trabalho ou CNIS, IR e comprovantes de renda.", "Apenas uma declaração assinada pelo estudante.", "Somente os três últimos extratos bancários."),
  "doc-2": opcoes(0, "Certificado e histórico escolar completo do ensino médio, emitidos pela escola.", "Declaração verbal do candidato.", "Somente o boletim do ENEM.", "Certidão de nascimento."),
  "doc-3": opcoes(2, "Somente o CPF do candidato.", "Apenas o documento do responsável pela casa.", "Documento com foto, CPF, renda e residência.", "Somente a certidão de nascimento."),
  "doc-4": opcoes(3, "Desistir automaticamente da inscrição.", "Enviar qualquer documento no lugar.", "Aguardar uma nova edição do PROUNI.", "Consultar a lista de documentos alternativos da instituição."),
  "doc-5": opcoes(1, "Apresentar somente seus próprios documentos.", "Comprovar também a situação do grupo familiar de origem.", "Não apresentar documentos de renda.", "Apresentar apenas uma declaração de independência."),
  "doc-6": opcoes(0, "Comprovar etnia ou deficiência conforme a modalidade.", "Basta declarar a renda familiar.", "Somente apresentar o histórico escolar.", "A cota é definida sem documentação."),
  "doc-7": opcoes(2, "A certidão só é exigida de aposentados.", "O documento é opcional.", "É exigida a Certidão Negativa ou Positiva de Benefícios do INSS dos integrantes do grupo familiar a partir de 18 anos.", "A certidão deve ser emitida pela Feevale."),
  "doc-8": opcoes(3, "Apresentar somente uma conta de luz.", "O IPTU serve para qualquer tipo de moradia.", "Não é preciso comprovar a moradia.", "Os documentos dependem da situação do imóvel."),
  "doc-9": opcoes(0, "DECORE, IRPJ, contrato social e extratos, conforme o caso.", "Somente o pró-labore.", "Apenas o contrato social.", "Somente uma declaração verbal."),
  "doc-10": opcoes(2, "Apenas o cartão do CNPJ.", "Somente os extratos bancários.", "Comprovante de MEI, declaração de renda, DASN-SIMEI e extratos.", "Somente a declaração anual do IRPF."),
  "doc-11": opcoes(1, "Toda declaração pode ser apenas digitalizada.", "A assinatura deve ser reconhecida ou feita pelo GOV.BR.", "Testemunhas sempre precisam ir ao cartório.", "A assinatura do candidato é dispensável."),
  "doc-12": opcoes(3, "Pensão nunca precisa ser comprovada.", "Basta informar o valor verbalmente.", "Somente a decisão judicial é necessária.", "Apresente decisão e comprovantes, ou declaração quando não houver decisão."),
  "doc-13": opcoes(0, "Apresente certidão conforme a situação familiar.", "Certidão de casamento é sempre dispensável.", "Somente o estudante pode emitir a certidão.", "Certidão de óbito substitui todos os documentos."),
  "doc-14": opcoes(2, "A matrícula pública pode ser mantida.", "Apenas a bolsa anterior precisa ser informada.", "É preciso cancelar o vínculo público antes da comprovação.", "Não é necessário apresentar nenhum documento."),
  "doc-15": opcoes(1, "Entregue uma declaração escrita à mão.", "Apresente o comprovante oficial de isenção da Receita.", "Substitua por um comprovante de residência.", "O documento não precisa ser substituído."),
  "prazo-1": opcoes(0, "Duas vezes por ano, com datas divulgadas no site oficial.", "Somente uma vez a cada dois anos.", "Todo mês, em datas fixas.", "Apenas quando a Feevale abrir vagas."),
  "prazo-2": opcoes(2, "Até o fim do curso.", "Não há prazo definido.", "O prazo indicado no edital, geralmente cerca de dez dias.", "Somente após o início das aulas."),
  "prazo-3": opcoes(1, "A pré-seleção é mantida sem documentos.", "A pré-seleção normalmente é cancelada.", "O prazo é transferido para o semestre seguinte.", "A vaga fica reservada indefinidamente."),
  "prazo-4": opcoes(3, "Não, só existem duas chamadas.", "Sim, mas apenas para quem já tem bolsa.", "Somente a Feevale pode criar lista de espera.", "Sim, ela convoca candidatos conforme surgem vagas."),
  "prazo-5": opcoes(0, "Primeira chamada, segunda chamada e lista de espera.", "Inscrição, matrícula e formatura.", "Somente uma chamada e entrevista.", "Prova, entrevista e estágio."),
  "prazo-6": opcoes(2, "A bolsa é liberada automaticamente sem matrícula.", "O candidato deve aguardar contato indefinidamente.", "Assine o termo e faça a matrícula após a aprovação.", "Basta enviar os documentos novamente."),
  "prazo-7": opcoes(1, "A instituição é responsável por todos os prazos.", "O estudante bolsista deve acompanhar e cumprir os prazos.", "Somente o MEC acompanha os prazos.", "Os prazos deixam de valer após a aprovação."),
  "renov-1": opcoes(3, "A renovação ocorre somente ao final do curso.", "A bolsa não precisa ser atualizada.", "A renovação depende apenas da renda.", "A bolsa é atualizada semestralmente."),
  "renov-2": opcoes(0, "É preciso aprovação em pelo menos 75% das disciplinas.", "Basta ser aprovado em uma disciplina.", "A frequência não interfere na bolsa.", "Não existe desempenho mínimo."),
  "renov-3": opcoes(2, "O trancamento sempre encerra a bolsa.", "O prazo é ilimitado.", "É possível trancar dentro do prazo permitido.", "O prazo é igual para todos os cursos."),
  "renov-4": opcoes(1, "A renda nunca é reavaliada.", "A instituição pode realizar reavaliação socioeconômica.", "Somente o MEC pode reavaliar a renda.", "A reavaliação ocorre apenas após a formatura."),
  "renov-5": opcoes(0, "Não, a bolsa integral cobre a disciplina novamente.", "Sim, sempre há cobrança integral.", "A cobrança depende do número de reprovações.", "Somente bolsistas parciais têm esse direito."),
  "perda-1": opcoes(2, "A bolsa só termina por pedido do estudante.", "Somente a mudança de curso encerra a bolsa.", "Fatores como reprovação, fraude, evasão ou vínculo público podem encerrá-la.", "A bolsa nunca pode ser encerrada."),
  "perda-2": opcoes(1, "É permitido reprovar em todas as disciplinas.", "É preciso aprovação mínima em 75% das disciplinas.", "Uma reprovação encerra sempre a bolsa.", "O desempenho não é analisado."),
  "perda-3": opcoes(3, "A renda nunca interfere depois da aprovação.", "A bolsa vira parcial automaticamente.", "Apenas a renda do estudante é considerada.", "Uma mudança substancial pode encerrar a bolsa."),
  "perda-4": opcoes(0, "Até duas vezes o prazo normal de integralização do curso.", "Somente até o primeiro semestre.", "Não existe prazo máximo.", "Até a conclusão de qualquer curso futuro."),
  "perda-5": opcoes(2, "O trancamento pode durar indefinidamente.", "O prazo é sempre de dois anos.", "O reingresso deve ocorrer dentro do prazo permitido.", "O prazo não depende do curso."),
  "perda-6": opcoes(1, "A bolsa continua normalmente.", "A bolsa é encerrada.", "A bolsa fica automaticamente parcial.", "A bolsa é transferida para a instituição pública."),
  "perda-7": opcoes(3, "O documento falso é corrigido sem consequência.", "A bolsa fica garantida após a matrícula.", "Apenas uma multa é aplicada.", "A bolsa pode ser encerrada, com direito à defesa."),
  "perda-8": opcoes(0, "Não. É permitido manter apenas uma bolsa por vez.", "Sim, sem qualquer limite.", "Sim, desde que sejam cursos diferentes.", "Somente duas bolsas integrais são permitidas."),
  "perda-9": opcoes(2, "O PROUNI e o FIES sempre podem ser acumulados.", "A regra vale apenas para bolsas parciais.", "Não é permitido usar bolsa PROUNI e FIES nas situações vedadas.", "O FIES cancela apenas a matrícula."),
  "perda-10": opcoes(1, "Suspensão e encerramento são a mesma coisa.", "Suspensão é temporária; encerramento é definitivo.", "O encerramento pode ser revertido automaticamente.", "A suspensão elimina todos os semestres usados."),
  "perda-11": opcoes(3, "A matrícula é cancelada imediatamente.", "O estudante perde o direito ao benefício.", "A bolsa passa a ser cobrada retroativamente.", "O usufruto pode ser suspenso até o período seguinte."),
  "dir-1": opcoes(0, "Não. A bolsa não precisa ser devolvida após a formatura.", "Sim, todo o valor deve ser pago.", "A devolução depende da renda final.", "Apenas metade do valor é devolvida."),
  "dir-2": opcoes(2, "O aproveitamento é automático.", "Nenhuma disciplina pode ser aproveitada.", "É possível solicitar análise de aproveitamento curricular.", "Apenas disciplinas do mesmo semestre são aceitas."),
  "dir-3": opcoes(3, "As duas bolsas são proibidas juntas.", "A iniciação científica cancela o PROUNI.", "Somente bolsistas parciais podem acumular benefícios.", "É possível ter PROUNI e bolsa de iniciação científica."),
  "dir-4": opcoes(0, "Pode ter até 90 dias de ausência justificada.", "Não possui nenhum direito adicional.", "Pode faltar sem realizar avaliações.", "A gravidez encerra a bolsa."),
  "dir-5": opcoes(2, "É um desconto na mensalidade.", "É uma bolsa exclusiva para professores.", "É um benefício mensal em dinheiro para alguns bolsistas integrais.", "É um empréstimo estudantil."),
  "dir-6": opcoes(1, "Abra uma conta poupança conjunta.", "Abra conta corrente individual e assine o termo na instituição.", "Receba automaticamente sem apresentar documentos.", "Solicite o pagamento diretamente ao banco sem a instituição."),
  "dir-7": opcoes(3, "O pagamento continua sem alterações.", "O benefício vira uma dívida.", "A Bolsa Permanência é encerrada definitivamente.", "O pagamento é interrompido durante a suspensão e pode retornar depois."),
  "dir-8": opcoes(0, "Não. A Feevale deve manter a bolsa dos estudantes já matriculados.", "Sim, a bolsa termina imediatamente.", "A bolsa vira financiamento.", "O estudante deve mudar de instituição."),
  "dir-9": opcoes(2, "São bolsas oferecidas somente a formados.", "São bolsas sem critérios socioeconômicos.", "São vagas não preenchidas que podem ser oferecidas a estudantes elegíveis.", "São bolsas com efeito retroativo garantido."),
  "dir-10": opcoes(1, "A seleção é feita manualmente pelo estudante.", "A seleção é automática e mensal, mas depende de recursos e procedimentos.", "O pagamento é sempre garantido pelo MEC.", "A seleção ocorre somente uma vez por ano."),
  "dir-11": opcoes(3, "A bolsa nunca pode ser encerrada.", "Somente a mudança de endereço encerra o benefício.", "O benefício termina apenas após a formatura.", "Pode terminar por perda dos critérios, encerramento da bolsa ou informação falsa."),
  "feevale-1": opcoes(0, "Pré-selecionados em chamada e classificados na lista de espera devem seguir as orientações de agendamento ou entrega de documentos da Feevale.", "Todos entregam documentos sem agendamento.", "A entrega ocorre somente por e-mail.", "A documentação é enviada diretamente ao MEC."),
  "feevale-2": opcoes(2, "A Feevale oferece transferências PROUNI regularmente.", "Toda transferência é automática.", "Atualmente não há previsão de vagas para transferências.", "A transferência depende somente do estudante."),
  "feevale-3": opcoes(1, "Solicite o comprovante na secretaria do curso.", "Solicite pelo e-mail prouni@feevale.br.", "O comprovante é enviado automaticamente.", "Solicite diretamente ao MEC."),
  "feevale-4": opcoes(3, "Alterações de matrícula não precisam ser comunicadas.", "Somente mudanças de endereço precisam ser informadas.", "O estudante deve aguardar o fim do semestre.", "Comunique alterações ao NAE e mantenha os contatos atualizados."),
  "feevale-5": opcoes(0, "O próprio bolsista ou seu representante legal.", "Qualquer colega de turma.", "Somente o professor responsável.", "Somente o MEC."),
  "feevale-6": opcoes(2, "Somente pela central do MEC.", "Apenas presencialmente no campus.", "Pelo NAE, usando os canais de contato da Feevale.", "Exclusivamente pelo portal do estudante."),
  "feevale-7": opcoes(1, "O reingresso é automático após o trancamento.", "Preencha o formulário da Feevale dentro do prazo.", "Basta voltar a frequentar as aulas.", "Solicite o reingresso diretamente ao MEC."),
  "feevale-8": opcoes(0, "Não. A Feevale não libera exceções para transferência ou troca de curso.", "A instituição pode cobrar taxa para analisar a transferência.", "Somente mudança de cidade permite transferência.", "A lei garante a transferência para qualquer curso da Feevale."),
  "feevale-9": opcoes(0, "A nota do ENEM e o tempo cursado devem atender aos critérios nacionais.", "Apenas a disponibilidade de vaga importa.", "A transferência independe da nota do ENEM.", "O curso de destino pode ter duração menor sem restrição."),
  "feevale-10": opcoes(2, "Não, menores podem ir sozinhos.", "Somente um colega precisa acompanhar.", "Sim, é obrigatório comparecer com um responsável.", "A presença de responsável só é exigida após a matrícula."),
};
